### PR TITLE
Notify Slack channel of build failures

### PR DESCRIPTION
**Pull request by giorgiosironi**
Expansion of https://github.com/elifesciences/elife-xpub/issues/1543 to other projects

### CODE REVIEW

**Comment by GiancarloFusiello** [comment]
is `maintainers.txt` a convention or just a file name you opted for?

**Comment by giorgiosironi** [comment]
It's an eLife language-agnostic convention, e.g. https://github.com/elifesciences/search/blob/develop/maintainers.txt normally contains email addresses and I have expanded its format to allow Slack channels. The terminology comes from the [open source world](https://api.drupal.org/api/drupal/core%21MAINTAINERS.txt/8.2.x) but I would be glad to find a more fitting name.

**Comment by GiancarloFusiello** [comment]
> It's an eLife language-agnostic convention, e.g. https://github.com/elifesciences/search/blob/develop/maintainers.txt normally contains email addresses and I have expanded its format to allow Slack channels. The terminology comes from the [open source world](https://api.drupal.org/api/drupal/core%21MAINTAINERS.txt/8.2.x) but I would be glad to find a more fitting name.

I don't mind the name. I think `slack_channels_to_notify` is more descriptive but is a bit long and no good if we decide to add more information.

**Comment by giorgiosironi** [comment]
> slack_channels_to_notify is more descriptive but is a bit long

The format cater for email notifications too, so it would be something like `notifications.txt`|`.notifications.txt`|...; easy to introduce later while maintaining backward compatibility, by checking for more than one allowed file names.

**Pull request merged**
